rss: atom.xml
fancybox: true
favicon: favicon.ico
fold: true
scratch_name: Scratch  # Notebook name of posts without categories variables
google_analytics: UA-83885261-2
inverse_sort: false
search:
  path: search.xml
  field: all
pin: Info
github_profile_card:
  max: 10
  username: CTFTraining
